name: CI

on: [push]

jobs:
  ecr-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Notify slack start
      id: slack-start
      uses: mahlstrom/actions2slack@v6
      with:
        github-run-id: $GITHUB_RUN_ID
        status: 'STARTED'
        slack-token: ${{ secrets.SLACK_TOKEN }}
        slack-channel: 'bottest'

    - uses: Terranovax/aws-ecr-deploy@v1
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        region: eu-west-1
        repo: podplayadmin-test-dev
        tags: latest,${{ github.sha }}

    - name: Slack if success
      id: slack-success
      uses: mahlstrom/actions2slack@v6
      with:
        github-run-id: $GITHUB_RUN_ID
        status: 'SUCCEEDED'
        slack-token: ${{ secrets.SLACK_TOKEN }}
        slack-channel: 'bottest'

    - name: Slack if failed
      if: ${{ failure() }}
      id: slack-failed
      uses: mahlstrom/actions2slack@v6
      with:
        github-run-id: $GITHUB_RUN_ID
        status: 'FAILED'
        slack-token: ${{ secrets.SLACK_TOKEN }}
        slack-channel: 'bottest'
